/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author User
 */
public class CadastroClient extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClient
     */
    public CadastroClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoCadastro = new javax.swing.JLabel();
        textoNomeUsuario = new javax.swing.JLabel();
        campoNomeUsuario = new javax.swing.JTextField();
        textoSenha = new javax.swing.JLabel();
        textoConfirmarSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        campoConfirmarSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        campoCPF = new javax.swing.JFormattedTextField();
        textoEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        textoCelular = new javax.swing.JLabel();
        campoCelular = new javax.swing.JFormattedTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textoStatus = new javax.swing.JLabel();
        checkboxSenha = new javax.swing.JCheckBox();
        botaoLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        textoCadastro.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        textoCadastro.setForeground(new java.awt.Color(0, 0, 0));
        textoCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoCadastro.setText("Cadastro Delivery");

        textoNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNomeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textoNomeUsuario.setText("Usuario");
        textoNomeUsuario.setToolTipText("");

        campoNomeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        campoNomeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeUsuario.setToolTipText("Digite seu nome de usuario");

        textoSenha.setBackground(new java.awt.Color(204, 204, 204));
        textoSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoSenha.setForeground(new java.awt.Color(0, 0, 0));
        textoSenha.setText("Senha");

        textoConfirmarSenha.setBackground(new java.awt.Color(204, 204, 204));
        textoConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoConfirmarSenha.setForeground(new java.awt.Color(0, 0, 0));
        textoConfirmarSenha.setText("Confirmar senha");

        campoSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoSenha.setForeground(new java.awt.Color(0, 0, 0));
        campoSenha.setToolTipText("Digite sua senha");

        campoConfirmarSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoConfirmarSenha.setForeground(new java.awt.Color(0, 0, 0));
        campoConfirmarSenha.setToolTipText("Confirme sua senha");

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CPF");

        campoCPF.setBackground(new java.awt.Color(255, 255, 255));
        campoCPF.setForeground(new java.awt.Color(0, 0, 0));
        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCPF.setToolTipText("Digite seu CPF");

        textoEndereco.setBackground(new java.awt.Color(204, 204, 204));
        textoEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoEndereco.setForeground(new java.awt.Color(0, 0, 0));
        textoEndereco.setText("Endereco");

        campoEndereco.setBackground(new java.awt.Color(255, 255, 255));
        campoEndereco.setForeground(new java.awt.Color(0, 0, 0));
        campoEndereco.setToolTipText("Digite seu endereco");

        textoCelular.setBackground(new java.awt.Color(204, 204, 204));
        textoCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoCelular.setForeground(new java.awt.Color(0, 0, 0));
        textoCelular.setText("N* Celular");

        campoCelular.setBackground(new java.awt.Color(255, 255, 255));
        campoCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            campoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCelular.setToolTipText("Digite seu numero de celular");

        botaoVoltar.setBackground(new java.awt.Color(255, 255, 255));
        botaoVoltar.setForeground(new java.awt.Color(0, 0, 0));
        botaoVoltar.setText("Voltar");
        botaoVoltar.setToolTipText("Voltar para a Tela de Login");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        botaoCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(255, 255, 255));
        botaoSair.setForeground(new java.awt.Color(0, 0, 0));
        botaoSair.setText("Sair");
        botaoSair.setToolTipText("Sair do aplicativo");
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Info");
        jLabel2.setToolTipText("Usuario >= 3 digitos\n\nCPF = 11 digitos\n\nEndereco >= 10 digitos\n\nCelular  = 11 digitos\n\nSenha >= 4 digitos\n");

        textoStatus.setBackground(new java.awt.Color(204, 204, 204));
        textoStatus.setForeground(new java.awt.Color(0, 0, 0));
        textoStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoStatus.setText("Aguardando preenchimento...");

        checkboxSenha.setForeground(new java.awt.Color(0, 0, 0));
        checkboxSenha.setText("Mostrar senhas");
        checkboxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxSenhaActionPerformed(evt);
            }
        });

        botaoLimpar.setBackground(new java.awt.Color(255, 255, 255));
        botaoLimpar.setForeground(new java.awt.Color(0, 0, 0));
        botaoLimpar.setText("Limpar");
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(botaoVoltar)
                .addGap(62, 62, 62)
                .addComponent(textoCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(textoNomeUsuario)
                                .addComponent(campoNomeUsuario)
                                .addComponent(textoSenha)
                                .addComponent(campoSenha)
                                .addComponent(campoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(textoEndereco)
                                .addComponent(campoEndereco)
                                .addComponent(textoConfirmarSenha)
                                .addComponent(campoConfirmarSenha)
                                .addComponent(textoCelular)
                                .addComponent(campoCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                            .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(checkboxSenha))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(textoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoCadastro)
                    .addComponent(botaoVoltar)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoNomeUsuario)
                            .addComponent(textoEndereco))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(textoCelular)
                        .addComponent(jLabel1)))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoSenha)
                    .addComponent(textoConfirmarSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxSenha))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textoStatus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(botaoLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private FastFoodService connectToServerRMI() throws RemoteException {
        try {
            Registry registry = LocateRegistry.getRegistry("localhost", 4444);
            return (FastFoodService) registry.lookup("FastFoodService");
        } catch (Exception e) {
            e.printStackTrace();
            throw new RemoteException("Falha ao conectar-se ao servidor RMI.");
        }
    }

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
            String usuario = campoNomeUsuario.getText();
            String senha1 = String.valueOf(campoSenha.getPassword());
            String endereco1 = campoEndereco.getText();

            try {
                FastFoodService fastFoodService = connectToServerRMI();
                boolean cadastroRealizado = fastFoodService.cadastrarUsuario(usuario, senha1, endereco1);

                if (cadastroRealizado) {
                    Timer timer = new Timer();
                    timer.schedule(new TimerTask() {
                        @Override
                        public void run() {
                            textoStatus.setText("Cadastro realizado com sucesso....");
                        }
                    }, 4000);

                    LoginClient loginClient = new LoginClient();

                    this.setVisible(false);

                    loginClient.setVisible(true);
                    loginClient.setLocationRelativeTo(null);

                }else {
                    textoStatus.setText("Usuário já cadastrado...");
                }
            } catch (RemoteException e) {
                e.printStackTrace();
                textoStatus.setText("Falha ao conectar-se ao servidor RMI.");
            }

        String nome_usuario = "";
        String cpf = "";
        String endereco = "";
        String celular = "";
        String senha = "";
        
        Boolean nome_usuario_check = false;
        Boolean cpf_check = false;
        Boolean endereco_check = false;
        Boolean celular_check = false;
        Boolean senha_check = false;
        
         
        if (this.campoNomeUsuario.getText().length() < 3){
            textoStatus.setText("Usuario precisa de 3 digitos...");
        }else{
            nome_usuario_check = true;
            nome_usuario = this.campoNomeUsuario.getText();
        }
        
        if(this.campoCPF.getText().length() < 11){
            textoStatus.setText("CPF precisa de 11 digitos...");
        }else{
            cpf_check = true;
            cpf = this.campoCPF.getText();
        }
        
        if (this.campoEndereco.getText().length() < 10){
            textoStatus.setText("Endereco precisa de 10 digitos...");
        }else{
            endereco_check = true;
            endereco = this.campoEndereco.getText();
        }
        
        if (this.campoCelular.getText().length() < 11){
            textoStatus.setText("Celular precisa de 11 digitos...");
        }else{
            celular_check = true;
            celular = this.campoCelular.getText();
        }
        
        if (this.campoSenha.getPassword().length < 4){
            textoStatus.setText("Senha precisa de 4 digitos...");   
        }else{
           senha_check = true;
           celular = this.campoCelular.getText();
        }
        
        //Fazer a verificao de todos os campos, para assim passar para o proxima pagina
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void checkboxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxSenhaActionPerformed
        if(checkboxSenha.isSelected()){
            campoSenha.setEchoChar((char)0);
            campoConfirmarSenha.setEchoChar((char)0);
        }else{
            campoSenha.setEchoChar('*');
            campoConfirmarSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxSenhaActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoNomeUsuario.setText("");
        campoCPF.setText("");
        campoEndereco.setText("");
        campoCelular.setText("");
        campoSenha.setText("");
        campoConfirmarSenha.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
                LoginClient loginClient = new LoginClient();

                this.setVisible(false);

                loginClient.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JFormattedTextField campoCelular;
    private javax.swing.JPasswordField campoConfirmarSenha;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNomeUsuario;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JCheckBox checkboxSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoCadastro;
    private javax.swing.JLabel textoCelular;
    private javax.swing.JLabel textoConfirmarSenha;
    private javax.swing.JLabel textoEndereco;
    private javax.swing.JLabel textoNomeUsuario;
    private javax.swing.JLabel textoSenha;
    private javax.swing.JLabel textoStatus;
    // End of variables declaration//GEN-END:variables
}
