/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author User
 */
public class CadastroClient extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClient
     */
    public CadastroClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoTitulo3 = new javax.swing.JLabel();
        textoTitulo2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        textoNomeUsuario = new javax.swing.JLabel();
        campoNomeUsuario = new javax.swing.JTextField();
        textoSenha = new javax.swing.JLabel();
        textoConfirmarSenha = new javax.swing.JLabel();
        campoSenha = new javax.swing.JPasswordField();
        campoConfirmarSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        campoCPF = new javax.swing.JFormattedTextField();
        textoEndereco = new javax.swing.JLabel();
        campoEndereco = new javax.swing.JTextField();
        textoCelular = new javax.swing.JLabel();
        campoCelular = new javax.swing.JFormattedTextField();
        botaoVoltar = new javax.swing.JButton();
        botaoCadastrar = new javax.swing.JButton();
        botaoSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textoStatus = new javax.swing.JLabel();
        checkboxSenha = new javax.swing.JCheckBox();
        botaoLimpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        textoTitulo4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textoTitulo5 = new javax.swing.JLabel();
        statusUsu = new javax.swing.JLabel();
        statusEnd = new javax.swing.JLabel();
        statusCPF = new javax.swing.JLabel();
        statusCell = new javax.swing.JLabel();
        statusSenha = new javax.swing.JLabel();

        textoTitulo3.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        textoTitulo3.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo3.setText("TELA DE LOGIN");

        textoTitulo2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        textoTitulo2.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo2.setText("All rights reserved for BurguerBOT FastFood Company LTDA");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        textoNomeUsuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoNomeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        textoNomeUsuario.setText("Usuario");
        textoNomeUsuario.setToolTipText("");

        campoNomeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        campoNomeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        campoNomeUsuario.setToolTipText("Digite seu nome de usuario");
        campoNomeUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoSenha.setBackground(new java.awt.Color(204, 204, 204));
        textoSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoSenha.setForeground(new java.awt.Color(0, 0, 0));
        textoSenha.setText("Senha");

        textoConfirmarSenha.setBackground(new java.awt.Color(204, 204, 204));
        textoConfirmarSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoConfirmarSenha.setForeground(new java.awt.Color(0, 0, 0));
        textoConfirmarSenha.setText("Confirmar senha");

        campoSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoSenha.setForeground(new java.awt.Color(0, 0, 0));
        campoSenha.setToolTipText("Digite sua senha");
        campoSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoSenha.setPreferredSize(new java.awt.Dimension(15, 24));

        campoConfirmarSenha.setBackground(new java.awt.Color(255, 255, 255));
        campoConfirmarSenha.setForeground(new java.awt.Color(0, 0, 0));
        campoConfirmarSenha.setToolTipText("Confirme sua senha");
        campoConfirmarSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoConfirmarSenha.setPreferredSize(new java.awt.Dimension(15, 24));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("CPF");

        campoCPF.setBackground(new java.awt.Color(255, 255, 255));
        campoCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoCPF.setForeground(new java.awt.Color(0, 0, 0));
        try {
            campoCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCPF.setToolTipText("Digite seu CPF");
        campoCPF.setPreferredSize(new java.awt.Dimension(15, 24));

        textoEndereco.setBackground(new java.awt.Color(204, 204, 204));
        textoEndereco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoEndereco.setForeground(new java.awt.Color(0, 0, 0));
        textoEndereco.setText("Endereco");

        campoEndereco.setBackground(new java.awt.Color(255, 255, 255));
        campoEndereco.setForeground(new java.awt.Color(0, 0, 0));
        campoEndereco.setToolTipText("Digite seu endereco");
        campoEndereco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textoCelular.setBackground(new java.awt.Color(204, 204, 204));
        textoCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoCelular.setForeground(new java.awt.Color(0, 0, 0));
        textoCelular.setText("N* Celular");

        campoCelular.setBackground(new java.awt.Color(255, 255, 255));
        campoCelular.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        campoCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            campoCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        campoCelular.setToolTipText("Digite seu numero de celular");
        campoCelular.setPreferredSize(new java.awt.Dimension(15, 24));

        botaoVoltar.setBackground(new java.awt.Color(255, 204, 153));
        botaoVoltar.setForeground(new java.awt.Color(0, 0, 0));
        botaoVoltar.setText("Voltar");
        botaoVoltar.setToolTipText("Voltar para a Tela de Login");
        botaoVoltar.setBorder(null);
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        botaoCadastrar.setBackground(new java.awt.Color(255, 204, 153));
        botaoCadastrar.setForeground(new java.awt.Color(0, 0, 0));
        botaoCadastrar.setText("Cadastrar");
        botaoCadastrar.setBorder(null);
        botaoCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarActionPerformed(evt);
            }
        });

        botaoSair.setBackground(new java.awt.Color(255, 204, 153));
        botaoSair.setForeground(new java.awt.Color(0, 0, 0));
        botaoSair.setText("Sair");
        botaoSair.setToolTipText("Sair do aplicativo");
        botaoSair.setBorder(null);
        botaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSairActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Info");
        jLabel2.setToolTipText("Usuario >= 3 digitos\n\nCPF = 11 digitos\n\nEndereco >= 10 digitos\n\nCelular  = 11 digitos\n\nSenha >= 4 digitos\n");

        textoStatus.setBackground(new java.awt.Color(204, 204, 204));
        textoStatus.setForeground(new java.awt.Color(0, 0, 0));
        textoStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoStatus.setText("Aguardando preenchimento...");

        checkboxSenha.setBackground(new java.awt.Color(255, 255, 255));
        checkboxSenha.setForeground(new java.awt.Color(0, 0, 0));
        checkboxSenha.setText("Mostrar senhas");
        checkboxSenha.setBorder(null);
        checkboxSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxSenhaActionPerformed(evt);
            }
        });

        botaoLimpar.setBackground(new java.awt.Color(255, 204, 153));
        botaoLimpar.setForeground(new java.awt.Color(0, 0, 0));
        botaoLimpar.setText("Limpar");
        botaoLimpar.setBorder(null);
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));

        textoTitulo4.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        textoTitulo4.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo4.setText("TELA DE CADASTRO");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("BurguerBOT");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pergunta-online.png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NOME.png"))); // NOI18N

        textoTitulo5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        textoTitulo5.setForeground(new java.awt.Color(255, 255, 255));
        textoTitulo5.setText("All rights reserved for BurguerBOT FastFood Company LTDA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(textoTitulo4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoTitulo5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(119, 119, 119))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textoTitulo4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(textoTitulo5)
                .addGap(15, 15, 15))
        );

        statusUsu.setBackground(new java.awt.Color(204, 204, 204));
        statusUsu.setForeground(new java.awt.Color(0, 0, 0));
        statusUsu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        statusEnd.setBackground(new java.awt.Color(204, 204, 204));
        statusEnd.setForeground(new java.awt.Color(0, 0, 0));
        statusEnd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        statusCPF.setBackground(new java.awt.Color(204, 204, 204));
        statusCPF.setForeground(new java.awt.Color(0, 0, 0));
        statusCPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        statusCell.setBackground(new java.awt.Color(204, 204, 204));
        statusCell.setForeground(new java.awt.Color(0, 0, 0));
        statusCell.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        statusSenha.setBackground(new java.awt.Color(204, 204, 204));
        statusSenha.setForeground(new java.awt.Color(0, 0, 0));
        statusSenha.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(566, 566, 566)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(10, 10, 10))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(campoSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addComponent(checkboxSenha))
                                            .addComponent(textoSenha))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(183, 183, 183)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(textoConfirmarSenha)
                                                    .addComponent(campoConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(statusSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel1)
                                                .addComponent(textoNomeUsuario)
                                                .addComponent(campoNomeUsuario)
                                                .addComponent(campoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                                            .addComponent(statusUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(statusCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(142, 142, 142)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(statusEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(textoEndereco)
                                                        .addComponent(campoEndereco)
                                                        .addComponent(textoCelular)
                                                        .addComponent(campoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(statusCell, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(textoStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(206, 206, 206))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(102, 102, 102))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoNomeUsuario)
                    .addComponent(textoEndereco))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(campoNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(campoEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(statusUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textoCelular)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(campoCelular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusCell, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoSenha, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textoConfirmarSenha))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoConfirmarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkboxSenha)
                    .addComponent(statusSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textoStatus)
                .addGap(2, 2, 2)
                .addComponent(jLabel2)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private FastFoodService connectToServerRMI() throws RemoteException {
        try {
            Registry registry = LocateRegistry.getRegistry("localhost", 4444);
            return (FastFoodService) registry.lookup("FastFoodService");
        } catch (Exception e) {
            e.printStackTrace();
            throw new RemoteException("Falha ao conectar-se ao servidor RMI.");
        }
    }

    private void botaoCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarActionPerformed
            String usuario = campoNomeUsuario.getText();
            String senha1 = String.valueOf(campoSenha.getPassword());
            String endereco1 = campoEndereco.getText();

            try {
                FastFoodService fastFoodService = connectToServerRMI();
                boolean cadastroRealizado = fastFoodService.cadastrarUsuario(usuario, senha1, endereco1);

                if (cadastroRealizado) {
                    Timer timer = new Timer();
                    timer.schedule(new TimerTask() {
                        @Override
                        public void run() {
                            textoStatus.setText("Cadastro realizado com sucesso....");
                        }
                    }, 4000);

                    LoginClient loginClient = new LoginClient();

                    this.setVisible(false);

                    loginClient.setVisible(true);
                    loginClient.setLocationRelativeTo(null);

                }else {
                    textoStatus.setText("Usuário já cadastrado...");
                }
            } catch (RemoteException e) {
                e.printStackTrace();
                textoStatus.setText("Falha ao conectar-se ao servidor RMI.");
            }

        String nome_usuario = "";
        String cpf = "";
        String endereco = "";
        String celular = "";
        String senha = "";
        
        Boolean nome_usuario_check = false;
        Boolean cpf_check = false;
        Boolean endereco_check = false;
        Boolean celular_check = false;
        Boolean senha_check = false;
        
         
        if (this.campoNomeUsuario.getText().length() < 3){
            statusUsu.setText("Usuario precisa de 3 digitos...");
        }else{
            nome_usuario_check = true;
            nome_usuario = this.campoNomeUsuario.getText();
            statusUsu.setText("");
        }
        
        cpf = this.campoCPF.getText();
        cpf = cpf.replaceAll("[^0-9]", "");
        if(cpf.length() != 11){
            statusCPF.setText("CPF precisa de 11 digitos...");
        }else{
            cpf_check = true;
            cpf = this.campoCPF.getText();
            statusCPF.setText("");
        }
        
        if (this.campoEndereco.getText().length() < 10){
            statusEnd.setText("Endereco precisa de 10 digitos...");
        }else{
            endereco_check = true;
            endereco = this.campoEndereco.getText();
            statusEnd.setText("");
        }
          
        if (this.campoSenha.getPassword().length < 4){
            textoStatus.setText("Senha precisa de 4 digitos...");   
        }else{
           senha_check = true;
           celular = this.campoCelular.getText();
        }   
    
        celular = this.campoCelular.getText();
        celular = celular.replaceAll("[^0-9]", "");
        if (celular.length() != 11){
            statusCell.setText("Celular precisa de 11 digitos...");
        }else{
            celular_check = true;
            celular = this.campoCelular.getText();
            statusCell.setText("");
        }
        
        //Fazer a verificao de todos os campos, para assim passar para o proxima pagina
    }//GEN-LAST:event_botaoCadastrarActionPerformed

    private void checkboxSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxSenhaActionPerformed
        if(checkboxSenha.isSelected()){
            campoSenha.setEchoChar((char)0);
            campoConfirmarSenha.setEchoChar((char)0);
        }else{
            campoSenha.setEchoChar('*');
            campoConfirmarSenha.setEchoChar('*');
        }
    }//GEN-LAST:event_checkboxSenhaActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        campoNomeUsuario.setText("");
        campoCPF.setText("");
        campoEndereco.setText("");
        campoCelular.setText("");
        campoSenha.setText("");
        campoConfirmarSenha.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void botaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSairActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_botaoSairActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
                LoginClient loginClient = new LoginClient();

                this.setVisible(false);

                loginClient.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastrar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JButton botaoSair;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JFormattedTextField campoCPF;
    private javax.swing.JFormattedTextField campoCelular;
    private javax.swing.JPasswordField campoConfirmarSenha;
    private javax.swing.JTextField campoEndereco;
    private javax.swing.JTextField campoNomeUsuario;
    private javax.swing.JPasswordField campoSenha;
    private javax.swing.JCheckBox checkboxSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel statusCPF;
    private javax.swing.JLabel statusCell;
    private javax.swing.JLabel statusEnd;
    private javax.swing.JLabel statusSenha;
    private javax.swing.JLabel statusUsu;
    private javax.swing.JLabel textoCelular;
    private javax.swing.JLabel textoConfirmarSenha;
    private javax.swing.JLabel textoEndereco;
    private javax.swing.JLabel textoNomeUsuario;
    private javax.swing.JLabel textoSenha;
    private javax.swing.JLabel textoStatus;
    private javax.swing.JLabel textoTitulo2;
    private javax.swing.JLabel textoTitulo3;
    private javax.swing.JLabel textoTitulo4;
    private javax.swing.JLabel textoTitulo5;
    // End of variables declaration//GEN-END:variables
}
